[package]
name = "hiveory-workspace-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hiveory-code-domain = { path = "../hiveory-code-domain" }
hiveory-protocol = { path = "../hiveory-protocol" }
cap-std.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

